export default {
  WishListContainer: 'div[class*=wishlistIconContainer]',
  WishListIcon: 'div[class*=wishlistIconContainer] > button',
  ToastButton: '.vtex-toast-container button',
  LoginEmail: '.vtex-login-2-x-inputContainerEmail input[type=text]',
  LoginPassword: '.vtex-login-2-x-inputContainerPassword input[type=password]',
  LoginButton: '.vtex-login-2-x-sendButton > button',
  ProductSummaryContainer: '.vtex-product-summary-2-x-container',
  AccounPage: '.vtex-account__page',
  WishlistDownloadButton: '.layout__container button',
  RelativeButton: '.div.relative > .vtex-button',
  AccountLoginButton: '.vtex-login-2-x-button',
  wishListSection: ':nth-child(6) > .vtex-account_menu-link',
  CloseToast: '.vtex-alert__close-icon',
  WishListOutLine: 'span[class*=outline]',
  WishListFill: 'span[class*=fill]',
  ThumbnailSwiper: '[data-testid=thumbnail-swiper]',
  WishListMenu: '#menu-wishlist',
}
