query CheckItem($shopperId: String!, $productId: String!, $sku: String) {
  checkList(shopperId: $shopperId, productId: $productId, sku: $sku) {
    inList
    listNames
    listIds
    message
  }
}
