query productsByIdentifier($ids: [ID!]) {
  productsByIdentifier(field: id, values: $ids)
    @context(provider: "vtex.search-graphql") {
      productName
      productId
    description
    link
    items {
      name
      itemId
      measurementUnit
      unitMultiplier
      referenceId {
        Value
      }
      images {
        imageUrl
        imageTag
        imageLabel
      }
      variations {
        name
        values
      }
      sellers {
        sellerId
        commertialOffer {
          AvailableQuantity
          Price
          PriceWithoutDiscount
          ListPrice
          Tax
          taxPercentage
          teasers {
            name
          }
          discountHighlights {
            name
          }
        }
      }
    }
  }
}
