query productsByIdentifier($ids: [ID!]) {
  productsByIdentifier(field: id, values: $ids)
    @context(provider: "vtex.search-graphql") {
    productName
    productId
    description
    link
    brand
    brandId
    categoryId
    clusterHighlights {
      id
      name
    }
    productClusters {
      id
      name
    }
    description
    skuSpecifications {
      field {
        originalName
        name
      }
      values {
        originalName
        name
      }
    }
    linkText
    properties {
      name
      values
    }
    propertyGroups {
      name
      properties
    }
    productReference
    titleTag
    metaTagDescription
    benefits {
      featured
      id
      name
      teaserType
      items {
        benefitProduct {
          description
          link
          linkText
          items {
            name
            referenceId {
              Key
              Value
            }
            images {
              imageId
              imageTag
              imageLabel
              imageUrl
              imageText
            }
          }
        }
        benefitSKUIds
        discount
        minQuantity
      }
    }
    specificationGroups {
      originalName
      name
      specifications {
        originalName
        name
        values
      }

    }
    priceRange {
      sellingPrice {
        highPrice
        lowPrice
      }
      listPrice {
        highPrice
        lowPrice
      }
    }
    items {
      name
      nameComplete
      complementName
      ean
      itemId
      measurementUnit
      unitMultiplier
      referenceId {
        Value
      }
      videos {
        videoUrl
      }
      images {
        imageUrl
        imageTag
        imageLabel
      }
      variations {
        name
        values
      }
      estimatedDateArrival
      sellers {
        sellerId
        sellerName
        sellerDefault
        commertialOffer {
          Installments {
            Value
            InterestRate
            TotalValuePlusInterestRate
            NumberOfInstallments
            PaymentSystemName
            PaymentSystemGroupName
            Name
          }
          AvailableQuantity
          spotPrice
          Price
          PriceWithoutDiscount
          ListPrice
          Tax
          taxPercentage
          RewardValue
          PriceValidUntil
          discountHighlights {
            name
          }
          giftSkuIds
          teasers {
            name
            conditions {
              minimumQuantity
              parameters {
                name
                value
              }
            }
            effects {
              parameters {
                name
                value
              }
            }
          }
          discountHighlights {
            name
          }
        }
      }
    }
  }
}
