name: '[PSH] Quality Engineering'

on:
  push:
    branches: 
      - master
      - main

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v2
    with:
      nodeLint: true
      nodeTest: false
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_wish-list-ts
      nodeSonarOrganization: vtex-apps
      dotnetLint: true
      dotnetSonar: true
      dotnetSonarProjectKey: vtex-apps_wish-list-dotnet
      dotnetSonarOrganization: vtex-apps
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
